# #==========================================================================
# |
# |  HeroStackDrops by Heroslender
# |  Site: http://heroslender.cf/plugins/HeroStackDrops/
# |  Discord: http://heroslender.cf/discord
# |
# #==========================================================================
# |
# | Restringir os itens que irao juntar no chao
# |
# | Nao tem suporte para data, so material mesmo
# | Talvez na proxima update coloque para data tambem
# |
# | Metodos disponiveis disponiveis:
# | WHITELIST - Apenas os itens listados aqui irao juntar
# | BLACKLIST - Todos os itens irao juntar menos os que se encontram aqui
# | DESATIVADO - Nao filtra os itens
# |
# | Itens sao os materiais dos itens que podem ou nao juntar
# |
# |    -> stack-on-spawn <-
# | Esta opção é para caso deseje que os itens se juntem direto
# | com outros itens por perto, não amostrando, assim, a animação
# | de dropar o item
# |
# |    -> raio-de-stack <-
# | Caso a opção `stack-on-spawn` esteja ativada, qual seria o raio
# | para procurar por itens para juntar
# |
# #==========================================================================
restringir-itens:
    metodo: 'WHITELIST'
    itens:
        - 'INK_SACK'
        - 'COAL'
        - 'COBBLESTONE'
        - 'REDSTONE'
mundos-bloqueados:
    - 'seu_mundo_bloqueado'
holograma:
    ativado: true
    texto: '&7{quantidade}x &e{nome}'
stack-on-spawn: false
raio-de-stack: 5
filtrar-mobs:
    metodo: DESATIVADO
    filtro:
        - player